import { dew } from "/npm:cheerio@0.22.0/index.dew.js";
export default dew();
import "/npm:cheerio@0.22.0/lib/cheerio.dew.js";
import "/npm:cheerio@0.22.0/package.json.dew.js";
import "/npm:cheerio@0.22.0/lib/parse.dew.js";
import "/npm:cheerio@0.22.0/lib/utils.dew.js";
import "/npm:lodash.assignin@4?dew";
import "/npm:lodash.bind@4?dew";
import "/npm:lodash.foreach@4?dew";
import "/npm:lodash.defaults@4?dew";
import "/npm:cheerio@0.22.0/lib/api/attributes.dew.js";
import "/npm:cheerio@0.22.0/lib/api/traversing.dew.js";
import "/npm:cheerio@0.22.0/lib/api/manipulation.dew.js";
import "/npm:cheerio@0.22.0/lib/api/css.dew.js";
import "/npm:cheerio@0.22.0/lib/api/forms.dew.js";
import "/npm:cheerio@0.22.0/lib/static.dew.js";
import "/npm:htmlparser2@3?dew";
import "/npm:@jspm/core@1/nodelibs/buffer.js";
import "/npm:dom-serializer@0.1?dew";
import "/npm:lodash.some@4?dew";
import "/npm:css-select@1.2?dew";
import "/npm:lodash.reject@4?dew";
import "/npm:lodash.filter@4?dew";
import "/npm:lodash.reduce@4?dew";
import "/npm:lodash.flatten@4?dew";
import "/npm:lodash.pick@4?dew";
import "/npm:lodash.map@4?dew";
import "/npm:lodash.merge@4?dew";
